# Generated by Django 5.2.7 on 2026-04-22 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitycard',
            name='cooldown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abilitycard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abilities/'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('tile_type', models.CharField(choices=[('GO', 'Go'), ('PROPERTY', 'Property'), ('RAILROAD', 'Railroad'), ('UTILITY', 'Utility'), ('TAX', 'Tax'), ('CHANCE', 'Chance'), ('COMMUNITY_CHEST', 'Community Chest'), ('JAIL', 'Jail'), ('FREE_PARKING', 'Free Parking'), ('GO_TO_JAIL', 'Go To Jail')], max_length=20)),
                ('group_color', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(default=0)),
                ('rent_base', models.IntegerField(default=0)),
                ('house_price', models.IntegerField(default=0)),
                ('hotel_price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tiles/')),
                ('description', models.TextField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='board.board')),
            ],
            options={
                'db_table': 'tiles',
                'ordering': ['position'],
                'unique_together': {('board', 'position')},
            },
        ),
    ]
