# Generated by Django 5.2.7 on 2026-04-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_abilitycard_cooldown_abilitycard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='characters/3d/'),
        ),
    ]
