# Generated by Django 5.2.7 on 2026-04-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_add_default_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='shape',
            field=models.CharField(choices=[('square', 'Kotak'), ('triangle', 'Segitiga'), ('circle', 'Bulat'), ('custom', 'Custom')], default='circle', max_length=20),
        ),
    ]
