# Generated by Django 5.2.7 on 2026-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_character_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='display_mode',
            field=models.CharField(
                choices=[('static', 'Statis (aset bawaan)'), ('customize', 'Kustom (unggah gambar)')],
                default='static',
                help_text='Statis: gambar dari aset standar. Kustom: unggah gambar petak.',
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='tile',
            name='path_line',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Sisi jalur di papan 9×9: 1=bawah, 2=kiri, 3=atas, 4=kanan',
            ),
        ),
        migrations.AddField(
            model_name='tile',
            name='rent_1house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='rent_2house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='rent_3house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='rent_4house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='rent_hotel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(blank=True, help_text='Ketentuan / teks petak', null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='group_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='hotel_price',
            field=models.IntegerField(default=0, help_text='Biaya upgrade ke hotel (jika berbeda)'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='house_price',
            field=models.IntegerField(default=0, help_text='Biaya bangun rumah / upgrade'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='rent_base',
            field=models.IntegerField(default=0, help_text='Sewa dasar (tanah kosong)'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(
                choices=[
                    ('GO', 'Mulai (GO)'),
                    ('PROPERTY', 'Properti'),
                    ('RAILROAD', 'Rel'),
                    ('UTILITY', 'Utilitas'),
                    ('TAX', 'Pajak'),
                    ('CHANCE', 'Kesempatan / Kartu'),
                    ('COMMUNITY_CHEST', 'Dana Umum'),
                    ('JAIL', 'Penjara / Kunjungan'),
                    ('FREE_PARKING', 'Parkir Gratis'),
                    ('GO_TO_JAIL', 'Masuk Penjara'),
                    ('AIRPORT', 'Bandara'),
                    ('FESTIVAL', 'Festival'),
                    ('TRAVEL', 'Perjalanan / Keliling Dunia'),
                ],
                max_length=24,
            ),
        ),
    ]
