# Generated by Django 5.2.7 on 2026-04-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_tile_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='code',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Kode unik petak (mis. start, banjarmasin); untuk data & CSS.',
                max_length=64,
            ),
        ),
    ]
