# Generated by Django 5.2.7 on 2026-04-23 14:38

from django.db import migrations, models


def create_builtin_classic_board(apps, schema_editor):
    Board = apps.get_model('board', 'Board')
    Tile = apps.get_model('board', 'Tile')
    from board.default_tiles_seed import seed_tiles_for_board

    builtin = Board.objects.filter(is_builtin=True).first()
    if builtin is None:
        builtin = Board.objects.create(
            name='Papan Jakarta',
            description='Papan bawaan: 32 petak DKI Jakarta (board/tiles.py). Dapat diedit di admin.',
            is_active=True,
            is_builtin=True,
        )
    if Tile.objects.filter(board=builtin).count() == 0:
        seed_tiles_for_board(builtin, Tile)


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_tile_code_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_builtin',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Papan bawaan aplikasi (satu: Papan Jakarta). Muncul di admin & permainan.',
            ),
        ),
        migrations.RunPython(create_builtin_classic_board, migrations.RunPython.noop),
    ]
