# Generated by Django 5.2.7 on 2026-04-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_papan_jakarta_resync_builtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Kode unik petak (mis. start, monas); untuk data & CSS.', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(choices=[('GO', 'Mulai (GO)'), ('PROPERTY', 'Properti'), ('RAILROAD', 'Rel'), ('UTILITY', 'Utilitas'), ('TAX', 'Pajak'), ('CHANCE', 'Kesempatan / Kartu'), ('COMMUNITY_CHEST', 'Dana Umum'), ('JAIL', 'Penjara / Kunjungan'), ('FREE_PARKING', 'Parkir Gratis'), ('GO_TO_JAIL', 'Masuk Penjara'), ('AIRPORT', 'Bandara'), ('FESTIVAL', 'Festival'), ('TRAVEL', 'Perjalanan / Keliling')], max_length=24),
        ),
    ]
